### ISSUE TITLE
Read-Only Mode

### ISSUE THREAD

**Issue by alexgaganashvili** [patrikx3/redis-ui#49]
Hello,

Is it possible to add a feature to connect to Redis hosts in read-only mode, that is to prevent users from being able to modify data stored in Redis?

Thanks.

**Comment by alexgaganashvili** [comment]
I would like to prevent users from adding/deleting/creating keys and values. I want them to only view the content.

Thanks

**Comment by alexgaganashvili** [comment]
Thanks for enabling the feature.
Question. According to the change log `"GUI elements removed and console is disabled"`, does that also mean that corresponding API calls are disabled as well? Jut want to confirm.
Btw, is there a flag or a parameter I can specify in the configmap to enable the feature?

Thanks.

**Comment by larrycai** [comment]
can u give more detail about this feature?

I tried in yaml (k8s)

````
          image: patrikx3/p3x-redis-ui
          command: ["p3x-redis"]
          args: ["--readonly-connections"]
````

but I still can delete the key/value in UI
