### ISSUE TITLE
Connection is closed.

### ISSUE THREAD

**Issue by Justman10000** [patrikx3/redis-ui#73]
Hi, I installed redis-ui and wanted to access my Redis instance... But only this comes up:

![grafik](https://user-images.githubusercontent.com/49990629/175972915-3f97ec0a-4fff-449f-b6e4-1666c93f843b.png)

**Comment by khairular** [comment]
![image](https://user-images.githubusercontent.com/108504745/179916549-cf769051-d7eb-4256-a24c-1662d21c1741.png)

I got this error as well, can't connect using the latest version
